version: '3.7'
services:
  procrastination-backend-pb:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv # optional
      - PB_ENCRYPTION # optional
    environment:
      PB_ENCRYPTION: ${PB_ENCRYPTION} # optional (Ensure this is a 32-character long encryption key https://pocketbase.io/docs/going-to-production/#enable-settings-encryption)
    ports:
      - '${PB_PORT:-8090}:8090'
    volumes:
      - ${PB_DIR_DATA:-./pb_data}:/pb_data
      - ${PB_DIR_PUBLIC:-./pb_public}:/pb_public
      - ${PB_DIR_HOOKS:-./pb_hooks}:/pb_hooks
      - ${PB_DIR_MIGRATIONS:-./pb_migrations}:/pb_migrations
    healthcheck: # optional, recommended since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
